"""
查询模板初始化文件
导出所有Cypher查询模板供其他模块使用
"""

# 边搜索模板
from .edge_search_templates import (
    EDGE_FULLTEXT_SEARCH,
    EDGE_SIMILARITY_SEARCH,
    EDGE_BFS_SEARCH,
    GET_RELEVANT_EDGES,
    GET_EDGE_INVALIDATION_CANDIDATES
)

# 节点搜索模板
from .node_search_templates import (
    NODE_FULLTEXT_SEARCH,
    NODE_SIMILARITY_SEARCH,
    NODE_BFS_SEARCH,
    GET_RELEVANT_NODES,
    GET_MENTIONED_NODES
)

# 情节搜索模板
from .episode_search_templates import (
    EPISODE_FULLTEXT_SEARCH,
    GET_EPISODES_BY_ENTITY,
    GET_EPISODES_BY_MENTIONS
)

# 社区搜索模板
from .community_search_templates import (
    COMMUNITY_FULLTEXT_SEARCH,
    COMMUNITY_SIMILARITY_SEARCH,
    GET_COMMUNITY_MEMBERS,
    GET_COMMUNITIES_BY_NODE
)

# 重排序模板
from .reranking_templates import (
    NODE_DISTANCE_RERANKER,
    EPISODE_MENTIONS_RERANKER,
    GET_EMBEDDINGS_FOR_NODES,
    GET_EMBEDDINGS_FOR_COMMUNITIES,
    GET_EMBEDDINGS_FOR_EDGES
)

__all__ = [
    # 边搜索模板
    'EDGE_FULLTEXT_SEARCH',
    'EDGE_SIMILARITY_SEARCH',
    'EDGE_BFS_SEARCH',
    'GET_RELEVANT_EDGES',
    'GET_EDGE_INVALIDATION_CANDIDATES',
    
    # 节点搜索模板
    'NODE_FULLTEXT_SEARCH',
    'NODE_SIMILARITY_SEARCH',
    'NODE_BFS_SEARCH',
    'GET_RELEVANT_NODES',
    'GET_MENTIONED_NODES',
    
    # 情节搜索模板
    'EPISODE_FULLTEXT_SEARCH',
    'GET_EPISODES_BY_ENTITY',
    'GET_EPISODES_BY_MENTIONS',
    
    # 社区搜索模板
    'COMMUNITY_FULLTEXT_SEARCH',
    'COMMUNITY_SIMILARITY_SEARCH',
    'GET_COMMUNITY_MEMBERS',
    'GET_COMMUNITIES_BY_NODE',
    
    # 重排序模板
    'NODE_DISTANCE_RERANKER',
    'EPISODE_MENTIONS_RERANKER',
    'GET_EMBEDDINGS_FOR_NODES',
    'GET_EMBEDDINGS_FOR_COMMUNITIES',
    'GET_EMBEDDINGS_FOR_EDGES'
]
