from datetime import datetime
from typing import Optional, List
from sqlmodel import SQLModel, Field


class RoleKnowledgeBase(SQLModel):
    """Role Knowledge Base Basic Model"""
    text: str = Field(..., description="Vectorized corpus required")
    role_id: str = Field(..., max_length=32, description="role unique identifier")
    type: str = Field(..., max_length=32, description="type")
    title: str = Field(..., max_length=255, description="title")
    source: Optional[str] = Field(None, max_length=255, description="source")
    tags: Optional[str] = Field(None, max_length=255, description="keyword")
    grade: float = Field(..., description="character level")
    relations: Optional[str] = Field(None, description="Relational Storage Knowledge Network")
    relations_role: Optional[str] = Field(None, description="shared role experience")


class RoleKnowledge(RoleKnowledgeBase, table=True):
    """Role Knowledge Base Database Model"""
    __tablename__ = "role_knowledge"
    
    id: Optional[str] = Field(default=None, primary_key=True, max_length=64, description="Unique ID generated by the snowflake algorithm")
    created_at: datetime = Field(
        default_factory=datetime.now,
        sa_column_kwargs={"server_default": "CURRENT_TIMESTAMP"},
        description="creation time"
    )
    updated_at: datetime = Field(
        default_factory=datetime.now,
        sa_column_kwargs={
            "server_default": "CURRENT_TIMESTAMP",
            "server_onupdate": "CURRENT_TIMESTAMP"
        },
        description="update time"
    )
    
    class Config:
        table_name = "role_knowledge"


class RoleKnowledgeCreate(RoleKnowledgeBase):
    """Create a Role Knowledge Base Request Model"""
    pass


class RoleKnowledgeUpdate(SQLModel):
    """Update the Role Knowledge Base Request Model"""
    text: Optional[str] = Field(None, description="Vectorized corpus required")
    role_id: Optional[str] = Field(None, max_length=32, description="role unique identifier")
    type: Optional[str] = Field(None, max_length=32, description="type")
    title: Optional[str] = Field(None, max_length=255, description="title")
    source: Optional[str] = Field(None, max_length=255, description="source")
    tags: Optional[str] = Field(None, max_length=255, description="keyword")
    grade: Optional[float] = Field(None, description="character level")
    relations: Optional[str] = Field(None, description="Relational Storage Knowledge Network")
    relations_role: Optional[str] = Field(None, description="shared role experience")


class RoleKnowledgeResponse(RoleKnowledgeBase):
    """Role Knowledge Base Response Model"""
    id: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class RoleKnowledgeBulkCreate(SQLModel):
    """Batch Create Role Knowledge Request Model"""
    items: List[RoleKnowledgeCreate] 